export const itemData = [
    {
        imageURL: "Rylais.webp",
        name: "Rylai's Crystal Scepter",
        stats: ["90AP", "300HP"],
        passive: ["slow", "20%"],
        cost: "2600",
        components: ["Blasting Wand", "Amplifying Tome", "Ruby Crystal", "915G"],
    },
    {
        imageURL: "Ludens.webp",
        name: "Luden's Echo",
        stats: ["90AP", "10CDR", "600M"],
        passive: ["10%", "cooldown", "bonus", "magic", "damage", "3"],
        cost: "3200",
        components: ["Lost Chapter", "Blasting Wand", "1050G"],
    },
    {
        imageURL: "Rabadons.webp",
        name: "Rabadon's Deathcap",
        stats: ["120AP"],
        passive: ["40%", "AP"],
        cost: "3600",
        components: ["Needlessly Large Rod", "Needlessly Large Rod", "1100G"],
    },
    {
        imageURL: "AmplifyingTome.webp",
        name: "Amplifying Tome",
        stats: ["20AP"],
        passive: [""],
        cost: "435",
        components: [""],
    },
    {
        imageURL: "BlastingWand.webp",
        name: "Blasting Wand",
        stats: ["40AP"],
        passive: [""],
        cost: "850",
        components: [""],
    },
    {
        imageURL: "HauntingGuise.webp",
        name: "Haunting Guise",
        stats: ["35AP", "200HP"],
        passive: ["stack", "second", "2%", "max", "10%"],
        cost: "1500",
        components: ["Ruby Crystal", "Amplifying Tome", "665G"],
    },
    {
        imageURL: "HextechProtobelt-01.webp",
        name: "Hextech Protobelt-01",
        stats: ["60AP", "10CDR", "300HP"],
        passive: ["dash", "magic", "damage", "bolts"],
        cost: "2500",
        components: ["Hextech Revolver", "Kindlegem", "650G"],
    },
    {
        imageURL: "",
        name: "",
        stats: [],
        passive: [],
        cost: "",
        components: [],
    },
]
