export const itemData = [
    {
        imageURL: "Rylais.webp",
        name: "Rylai's Crystal Scepter",
        stats: ["90AP", "300HP"],
        passive: ["slow", "20%"],
        cost: "2600",
        components: ["Blasting Wand", "Amplifying Tome", "Ruby Crystal", "915G"],
    },
    {
        imageURL: "Ludens.webp",
        name: "Luden's Echo",
        stats: ["90AP", "10CDR", "600M"],
        passive: ["10%", "cooldown", "bonus", "magic", "damage", "3"],
        cost: "3200",
        components: ["Lost Chapter", "Blasting Wand", "1050G"],
    },
    {
        imageURL: "Rabadons.webp",
        name: "Rabadon's Deathcap",
        stats: ["120AP"],
        passive: ["40%", "AP"],
        cost: "3600",
        components: ["Needlessly Large Rod", "Needlessly Large Rod", "1100G"],
    },
    {
        imageURL: "AmplifyingTome.webp",
        name: "Amplifying Tome",
        stats: ["20AP"],
        passive: [""],
        cost: "435",
        components: [""],
    },
    {
        imageURL: "BlastingWand.webp",
        name: "Blasting Wand",
        stats: ["40AP"],
        passive: [""],
        cost: "850",
        components: [""],
    },
    {
        imageURL: "HauntingGuise.webp",
        name: "Haunting Guise",
        stats: ["35AP", "200HP"],
        passive: ["stack", "second", "2%", "max", "10%"],
        cost: "1500",
        components: ["Ruby Crystal", "Amplifying Tome", "665G"],
    },
    {
        imageURL: "HextechProtobelt-01.webp",
        name: "Hextech Protobelt-01",
        stats: ["60AP", "10CDR", "300HP"],
        passive: ["dash", "magic", "damage", "bolts"],
        cost: "2500",
        components: ["Hextech Revolver", "Kindlegem", "650G"],
    },
    {
        imageURL: "HextechRevolver.webp",
        name: "Hextech Revolver",
        stats: ["40AP"],
        passive: ["basic", "attack", "shocks", "magic", "damage"],
        cost: "1050",
        components: ["Amplifying Tome", "Amplifying Tome", "180G"],
    },
    {
        imageURL: "Kindlegem.webp",
        name: "Kindlegem",
        stats: ["10CDR", "200HP"],
        passive: [""],
        cost: "800",
        components: ["Ruby Crystal"],
    },
    {
        imageURL: "Liandrys.webp",
        name: "Liandry's Torment",
        stats: ["75AP", "300HP"],
        passive: ["dot", "4.5%", "maximum", "health", "7.5%", "immobilized", "stack", "second", "2%", "max", "10%"],
        cost: "3100",
        components: ["Haunting Guise", "Blasting Wand", "750G"],
    },
    {
        imageURL: "Morellonomicon.webp",
        name: "Morellonomicon",
        stats: ["70AP", "300HP"],
        passive: ["grievous", "wounds"],
        cost: "3000",
        components: ["Blasting Wand", "Oblivion Orb", "550G"],
    },
    {
        imageURL: "RodofAges.webp",
        name: "Rod of Ages",
        stats: ["60AP", "300HP", "300M"],
        passive: ["20HP", "10M", "4AP", "minute", "restore", "mana", "health"],
        cost: "2600",
        components: ["Blasting Wand", "Catalyst of Aeons", "650G"],
    },
    {
        imageURL: "RubyCrystal.webp",
        name: "Ruby Crystal",
        stats: ["150HP"],
        passive: [""],
        cost: "400",
        components: [""],
    },
    {
        imageURL: "",
        name: "",
        stats: [""],
        passive: [""],
        cost: "",
        components: [""],
    },
]
